name: Sending guardduty notifications to sns
run-name: Sending guardduty notifications to sns

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:

jobs:
  # code:
  #   name: Obtaining the code
  #   runs-on: ubuntu-latest
      
  build_and_deploy:
    name: Building and deploying
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./architeture2/guardduty_to_sns
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: bash $GITHUB_WORKSPACE/.github/scripts/py_build.sh $GITHUB_WORKSPACE/architeture2/guardduty_to_sns/lambda_function $GITHUB_WORKSPACE/architeture2/guardduty_to_sns/build lambda_mock.zip Function   
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
      - run: terraform destroy -auto-approve
        if: ${{ failure() || cancelled() }}
      - uses: actions/upload-artifact@v3
        if: ${{ success() || failure() }}
        with:
          name: tfstate_guardduty_to_sns
          path: architeture2/guardduty_to_sns/terraform.tfstate
          if-no-files-found: error 
