name: Deploying lambda function
run-name: Deploying lambda function

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  # code:
  #   name: Obtaining the code
  #   runs-on: ubuntu-latest

  # unit_test:
  #   name: Testing function
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./architeture2
  #   steps:
  #     - name: Check out repo's default branch
  #       uses: actions/checkout@v3

  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #         cache: 'pip'   

  #     - name: Install dependencies
  #       run: pip install -r ./tests/requirements.txt  

  #     - uses: aws-actions/setup-sam@v2
  #       with:
  #         use-installer: true

  #     - run: python -m pytest tests/unit -v
      
  build_and_deploy:
    # needs: [unit_test]
    name: Building and deploying
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./architeture2
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
        
      # - name: Install dependencies
      #   run: pip install -r ./lambda_function/requirements.txt  

      # - uses: aws-actions/setup-sam@v2
      #   with:
      #     use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: bash ../.github/scripts/py_build.sh $GITHUB_WORKSPACE/architeture2/lambda_function $GITHUB_WORKSPACE/architeture2/build hello_function.zip Function   

  # integration_test:
  #   needs: [build_and_deploy]
  #   name: Testing api
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./architeture2
  #   steps:
  #     - name: Check out repo's default branch
  #       uses: actions/checkout@v3

  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #         cache: 'pip'   

  #     - name: Install dependencies
  #       run: pip install -r ./tests/requirements.txt  

  #     - uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - run: python -m pytest tests/integration -v
  #       env:
  #         AWS_SAM_STACK_NAME: testing-gha